# register_nightly.ps1
# Register a nightly Windows Task Scheduler entry that runs the stewardship
# scripts (drift_check, auto_memory_housekeep, optionally a generated
# briefing). User-facing helper — run once per machine to enable.
#
# Usage:
#   .\register_nightly.ps1                     # default: 03:00 daily, dry-run housekeep
#   .\register_nightly.ps1 -At "02:30"         # custom time
#   .\register_nightly.ps1 -ApplyHousekeep     # actually archive stale memory
#   .\register_nightly.ps1 -Unregister         # remove the task

[CmdletBinding()]
param(
    [string]$At = "03:00",
    [string]$TaskName = "stewardship-nightly-steward",
    [switch]$ApplyHousekeep,
    [switch]$Unregister
)

$ErrorActionPreference = "Stop"

if ($Unregister) {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Unregistered: $TaskName" -ForegroundColor Green
    } else {
        Write-Host "No task named $TaskName found." -ForegroundColor Yellow
    }
    exit 0
}

$pluginRoot = $PSScriptRoot | Split-Path -Parent
$logDir = Join-Path $env:LOCALAPPDATA "stewardship-plugin\logs"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

$logFile = Join-Path $logDir "nightly.log"

$housekeepFlag = if ($ApplyHousekeep) { "--apply" } else { "" }

# Resolve a Python launcher. Windows typically ships `python`/`py`; macOS and
# Linux ship `python3`. Bake the resolved command into the wrapper so the
# scheduled task does not depend on PATH ordering at run time.
$pythonExe = $null
foreach ($cand in @('python3', 'python', 'py')) {
    if (Get-Command $cand -ErrorAction SilentlyContinue) { $pythonExe = $cand; break }
}
if (-not $pythonExe) {
    Write-Error "No Python interpreter found on PATH (tried python3, python, py). Install Python 3 and re-run."
    exit 1
}

# The ps1 wrapper that the scheduler invokes. We write it once into the log dir
# so the scheduler has a stable target (rather than referencing the plugin
# install path which can move).
$wrapperPath = Join-Path $logDir "run-nightly.ps1"

$wrapperContent = @"
# Auto-generated by register_nightly.ps1. Edit to customize.
`$ErrorActionPreference = "Continue"
`$logFile = "$logFile"
"--- nightly steward run: `$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ---" | Out-File -Append `$logFile

# 1. Drift check
"## drift_check" | Out-File -Append `$logFile
$pythonExe "$pluginRoot/scripts/drift_check.py" 2>&1 | Out-File -Append `$logFile

# 2. Auto-memory housekeeping
"## auto_memory_housekeep" | Out-File -Append `$logFile
$pythonExe "$pluginRoot/scripts/auto_memory_housekeep.py" $housekeepFlag 2>&1 | Out-File -Append `$logFile

# 3. Horizon-scan cadence check (deterministic reminder; the scan itself is interactive)
"## horizon_scan" | Out-File -Append `$logFile
$pythonExe "$pluginRoot/scripts/horizon_scan_schedule.py" 2>&1 | Out-File -Append `$logFile

# 4. Morning briefing render
"## morning_briefing" | Out-File -Append `$logFile
$pythonExe "$pluginRoot/scripts/render_briefing.py" 2>&1 | Out-File -Append `$logFile

"--- end ---`n" | Out-File -Append `$logFile
"@

$wrapperContent | Out-File -FilePath $wrapperPath -Encoding utf8

# Register/replace the task
$action = New-ScheduledTaskAction -Execute "pwsh.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$wrapperPath`""
$trigger = New-ScheduledTaskTrigger -Daily -At $At
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null

Write-Host "Registered task: $TaskName" -ForegroundColor Green
Write-Host "  Runs daily at $At"
Write-Host "  Wrapper script: $wrapperPath"
Write-Host "  Log file: $logFile"
Write-Host ""
Write-Host "To run immediately as a smoke test:" -ForegroundColor Cyan
Write-Host "  Start-ScheduledTask -TaskName $TaskName"
Write-Host "To unregister:" -ForegroundColor Cyan
Write-Host "  .\register_nightly.ps1 -Unregister"
