# register_nightly.ps1
# Register a nightly Windows Task Scheduler entry that runs the stewardship
# scripts (drift_check, auto_memory_housekeep, optionally a generated
# briefing). User-facing helper — run once per machine to enable.
#
# Usage:
#   .\register_nightly.ps1                     # default: 03:00 daily, dry-run housekeep
#   .\register_nightly.ps1 -At "02:30"         # custom time
#   .\register_nightly.ps1 -ApplyHousekeep     # actually archive stale memory
#   .\register_nightly.ps1 -LearningScript "<...>/plugins/learning/scripts/synthesize_nightly.py"
#                                              # also mine instincts nightly (learning plugin)
#   .\register_nightly.ps1 -Unregister         # remove the task
#
# -LearningScript is an explicit path because the learning plugin installs to its
# own versioned dir, which this script (running from stewardship) cannot resolve.

[CmdletBinding()]
param(
    [string]$At = "03:00",
    [string]$TaskName = "stewardship-nightly-steward",
    [switch]$ApplyHousekeep,
    [string]$LearningScript,
    [switch]$Unregister
)

$ErrorActionPreference = "Stop"

if ($Unregister) {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Unregistered: $TaskName" -ForegroundColor Green
    } else {
        Write-Host "No task named $TaskName found." -ForegroundColor Yellow
    }
    exit 0
}

$pluginRoot = $PSScriptRoot | Split-Path -Parent
$logDir = Join-Path $env:LOCALAPPDATA "stewardship-plugin\logs"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

$logFile = Join-Path $logDir "nightly.log"

$housekeepFlag = if ($ApplyHousekeep) { "--apply" } else { "" }

# Resolve a Python launcher. Windows typically ships `python`/`py`; macOS and
# Linux ship `python3`. Bake the resolved ABSOLUTE path into the wrapper so the
# scheduled task does not depend on PATH ordering at run time — a bare name can
# resolve to a different (or vanished) interpreter at 03:00 than it did here,
# failing with no output in the log.
$pythonExe = $null
foreach ($cand in @('python3', 'python', 'py')) {
    $cmd = Get-Command $cand -ErrorAction SilentlyContinue
    if ($cmd) { $pythonExe = $cmd.Source; break }
}
if (-not $pythonExe) {
    Write-Error "No Python interpreter found on PATH (tried python3, python, py). Install Python 3 and re-run."
    exit 1
}

# The wrapper bakes absolute paths to this plugin's scripts. If this script is
# running from a movable location (a dev clone, a versioned install cache),
# those baked paths rot when the source moves or the version bumps — the
# stable choice is the live marketplace checkout under ~/.claude/plugins/marketplaces/.
$marketplacesRoot = Join-Path $HOME ".claude\plugins\marketplaces"
if (-not $pluginRoot.StartsWith($marketplacesRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    Write-Warning ("Registering from a movable checkout: {0}" -f $pluginRoot)
    Write-Warning ("Baked paths break if this directory moves or is re-versioned. Prefer running this script from the marketplace checkout, e.g.:")
    Write-Warning ("  $marketplacesRoot\<marketplace>\plugins\stewardship\scripts\register_nightly.ps1")
}

# The ps1 wrapper that the scheduler invokes. We write it once into the log dir
# so the scheduler has a stable target (rather than referencing the plugin
# install path which can move).
$wrapperPath = Join-Path $logDir "run-nightly.ps1"

if ($LearningScript -and -not (Test-Path $LearningScript)) {
    Write-Error "LearningScript not found: $LearningScript — fix the path before registering (a rotten path would fail only at 03:00)."
    exit 1
}

# Optional learning-plugin synthesis step. Runs BEFORE the briefing render so the
# briefing reads the report this step just wrote (both resolve the same
# data-root path: <LEARNING_DATA_ROOT>/last_mine_report.json).
$learningStep = ""
if ($LearningScript) {
    $learningStep = @"
# 4. Headless instinct synthesis (learning plugin) — mines ALL observed projects
Invoke-Step "synthesize_nightly" { & "$pythonExe" "$LearningScript" --apply 2>&1 }

"@
}

# Each step runs through Invoke-Step so a nonzero exit is stamped into the log
# AND the wrapper exits nonzero — Task Scheduler's LastTaskResult then surfaces
# the failure instead of reporting success while every step fails silently.
$wrapperContent = @"
# Auto-generated by register_nightly.ps1. Edit to customize.
`$ErrorActionPreference = "Continue"
`$logFile = "$logFile"
`$script:failed = `$false
function Invoke-Step([string]`$name, [scriptblock]`$body) {
    "## `$name" | Out-File -Append `$logFile
    & `$body | Out-File -Append `$logFile
    if (`$LASTEXITCODE -ne 0) {
        "## `$name FAILED (exit `$LASTEXITCODE)" | Out-File -Append `$logFile
        `$script:failed = `$true
    }
}
"--- nightly steward run: `$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ---" | Out-File -Append `$logFile

# 1. Drift check
Invoke-Step "drift_check" { & "$pythonExe" "$pluginRoot/scripts/drift_check.py" 2>&1 }

# 2. Auto-memory housekeeping
Invoke-Step "auto_memory_housekeep" { & "$pythonExe" "$pluginRoot/scripts/auto_memory_housekeep.py" $housekeepFlag 2>&1 }

# 3. Horizon-scan cadence check (deterministic reminder; the scan itself is interactive)
Invoke-Step "horizon_scan" { & "$pythonExe" "$pluginRoot/scripts/horizon_scan_schedule.py" 2>&1 }

$learningStep
# 5. Morning briefing render
Invoke-Step "morning_briefing" { & "$pythonExe" "$pluginRoot/scripts/render_briefing.py" 2>&1 }

if (`$script:failed) {
    "--- end (FAILURES — see FAILED markers above) ---`n" | Out-File -Append `$logFile
    exit 1
}
"--- end ---`n" | Out-File -Append `$logFile
"@

$wrapperContent | Out-File -FilePath $wrapperPath -Encoding utf8

# Register/replace the task
$action = New-ScheduledTaskAction -Execute "pwsh.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$wrapperPath`""
$trigger = New-ScheduledTaskTrigger -Daily -At $At
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null

Write-Host "Registered task: $TaskName" -ForegroundColor Green
Write-Host "  Runs daily at $At"
Write-Host "  Wrapper script: $wrapperPath"
Write-Host "  Log file: $logFile"
Write-Host ""
Write-Host "To run immediately as a smoke test:" -ForegroundColor Cyan
Write-Host "  Start-ScheduledTask -TaskName $TaskName"
Write-Host "To unregister:" -ForegroundColor Cyan
Write-Host "  .\register_nightly.ps1 -Unregister"
