#!/usr/bin/env python3
"""Generate docs/skill-index.md — a discovery table of every skill and agent.

Reuses the frontmatter parser from ci/lint-frontmatter.py (importlib-loaded,
hyphenated filename). Generation beats hand-writing here only because that
parser already exists and skills churn with releases.

Usage:
    python3 ci/gen-skill-index.py --write    # regenerate docs/skill-index.md
    python3 ci/gen-skill-index.py --check    # exit 1 if the file is out of date
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = ROOT / "docs" / "skill-index.md"

_spec = importlib.util.spec_from_file_location(
    "lint_frontmatter", ROOT / "ci" / "lint-frontmatter.py"
)
_lint = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_lint)

MAX_DESC = 160


def _describe(path: Path) -> tuple[str, str]:
    """Return (name, truncated description) from a skill/agent/command file."""
    block = _lint.extract_frontmatter(path.read_text(encoding="utf-8")) or ""
    # Commands name themselves by filename, so fall back to the stem (not the
    # parent dir "commands"); skills fall back to their containing skill dir.
    fallback = path.stem if path.parent.name == "commands" else path.parent.name
    name = _lint.key_value(block, "name") or fallback
    desc = (_lint.key_value(block, "description") or "").replace("|", "\\|")
    desc = " ".join(desc.split())
    if len(desc) > MAX_DESC:
        desc = desc[: MAX_DESC - 1].rsplit(" ", 1)[0] + "…"
    return name, desc


def _rows(paths: list[Path], plugin_index: int) -> list[str]:
    rows = []
    for p in paths:
        plugin = p.relative_to(ROOT).parts[plugin_index]
        name, desc = _describe(p)
        rows.append(f"| {plugin} | `{name}` | {desc} |")
    return rows


def generate() -> str:
    skills = sorted(ROOT.glob("plugins/*/skills/*/SKILL.md"))
    agents = sorted(ROOT.glob("plugins/*/agents/*.md"))
    commands = sorted(ROOT.glob("plugins/*/commands/*.md"))
    lines = [
        "# Skill, Agent & Command Index",
        "",
        "> Generated by `python3 ci/gen-skill-index.py --write` — do not hand-edit.",
        "> `scripts/verify.sh` runs `--check` and fails when this file drifts from",
        "> the frontmatter it is generated from.",
        "",
        f"## Skills ({len(skills)})",
        "",
        "| Plugin | Skill | Description |",
        "|---|---|---|",
        *_rows(skills, 1),
        "",
        f"## Agents ({len(agents)})",
        "",
        "| Plugin | Agent | Description |",
        "|---|---|---|",
        *_rows(agents, 1),
        "",
        f"## Commands ({len(commands)})",
        "",
        "| Plugin | Command | Description |",
        "|---|---|---|",
        *_rows(commands, 1),
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    content = generate()
    if "--write" in argv:
        INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        INDEX_PATH.write_text(content, encoding="utf-8", newline="\n")
        print(f"gen-skill-index: wrote {INDEX_PATH.relative_to(ROOT)}")
        return 0
    # default: --check
    existing = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.is_file() else ""
    if existing != content:
        print(
            "gen-skill-index: docs/skill-index.md is out of date. "
            "Run: python3 ci/gen-skill-index.py --write"
        )
        return 1
    print("gen-skill-index: up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
